version: '3'
services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile.laravel
    ports:
      - '8000:9000'  # Adjust the ports as needed
    depends_on:
      - database
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.react
    ports:
      - '3000:3000'  # Adjust the ports as needed
  database:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ICSHC
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306'  # Adjust the ports as needed
